# Generated by Django 3.0 on 2020-02-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResultHis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_x', models.TextField(blank=True, max_length=200)),
                ('num_y', models.TextField(blank=True, max_length=200)),
                ('operation', models.TextField(blank=True, max_length=200)),
                ('num_result', models.TextField(blank=True, max_length=200)),
            ],
        ),
    ]
